name: CI
on:
  push:
    branches: [ "v2.1" ]
  pull_request:
    branches: [ "v2.1" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install gcc-multilib
        run: |
          sudo apt update
          sudo apt install gcc-multilib -y
      - name: Run a multi-line script
        run: cd src && ls -l

      # - name: Upload Lib to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: "src/libluajit.a"
      #     asset_name: mything
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is my release text"

      # https://hedzr.com/tech/nology/github-actions-resource-not-accesible-by-integration/ 
      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "src/libluajit.a"
          tag: false
          draft: false 