name: CI
on:
  push:
    branches: [ "v2.1" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: build-android
        run: sudo ./build-android.sh

      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "android.tar"
          tag: false
          draft: false 