# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "v2.1" branch
  push:
    branches: [ "v2.1" ]
  pull_request:
    branches: [ "v2.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install gcc-multilib
        run: |
          sudo apt update
          sudo apt install gcc-multilib -y

      - name: Run a multi-line script
        run: wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip

      - name: Run a multi-line script
        run: unzip android-ndk-r14b-linux-x86_64.zip -d ./

      - name: Run a multi-line script
        run: ls -l

      - name: Run a multi-line script
        run: chmod +x ./build-r14-linux.sh

      # Runs a single command using the runners shell
      - name: Run a multi-line script
        run: ls -l

      # Runs a single command using the runners shell
      - name: Run a multi-line script
        run: ./build-r14-linux.sh

      - name: Run a multi-line script
        run: ls -l

      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "src/libluajit.a"
          tags: true
          draft: true